import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import Script from 'next/script'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.4.4/dist/flowbite.min.css" />
      </head>
      <body>
        {children}
        <Script src="https://unpkg.com/flowbite@1.4.0/dist/flowbite.js" async />
      </body>
    </html>
  )
}
